[package]
name = "snazzy"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
description = "Example project using prost-build"
edition = "2018"

[dependencies]
prost = "0.8"

[build-dependencies]
prost-build = "0.8"
